PAD_TOKEN: <PAD>
UNK_TOKEN: <UNK>
PAD_IDX: 0
UNK_IDX: 1
BATCH_SIZE: 128
DROP_LOCATION: true
NUM_LSTM_LAYERS: 2
HIDDEN_DIM: 64
DROPOUT: 0.28
OUTPUT_DIM: 1
EMB_DIM: 100
EPOCHS: 50
LEARNING_RATE: 0.0003
LOWERCASE: true
MAX_LENGTH: 200
SEED: 28
STRIP_MULTIPLE_WHITESPACE: true
TRAIN_TEST_SPLIT: 0.8
USE_KEYWORD: true
UPPERCASE: false
VOCAB_SIZE: 10000
NUM_WORKERS: 0
METRIC_THRESHOLD: 0.5
INFERENCE_THRESHOLD: 0.5
EARLY_STOP_PATIENCE: 5
EARLY_STOP_MIN_DELTA: 0.001
ARTIFACT_DIR: ./artifacts/
IMAGE_DIR: ./images/
DATA_DIR: ./data/
CHECKPOINT_PATH: ./model/
EMB_PATH: ./data/glove.6B.100d.txt
TRAIN_PATH: ./data/train.csv
TEST_PATH: ./data/test.csv
DEVICE: cuda
